### ISSUE TITLE
issue with a converter

### ISSUE THREAD

**Issue by kiduyu-klaus** [Helias/EPUB-to-PDF#1]
am grateful for this code you have offered but i have an issue with the ebook convert requirement.  Also , there is the TelegramDeprecationWarning issue.

here is the error am getting.
<img width="498" alt="Screenshot_11" src="https://user-images.githubusercontent.com/24317021/86237976-97b22100-bb51-11ea-8366-f2348f1f642e.png">
i will really appreciate your help. thankyou

**Comment by Helias** [comment]
Warning fixed in the last commit, thanks for your report.

About the error, it's `No such file or directory 'Jack_Reacher_Book_01_Lee_....pdf`, I think that the bot has no permission to download/create the file in your local machine, so try to change the permissions to the directory.

Let me know if you need any help.

**Comment by Helias** [comment]
@kiduyu-klaus did you solve?

**Comment by kiduyu-klaus** [comment]
am getting the same error when I try to convert an epub. I have changed the permissions,  even tried on a new folder.

when I try the conversion, the epub is added to the folder but the pdf is throwing a  " FileNotFoundError: [Errno 2] No such file or directory " error.

**Comment by Helias** [comment]
how did you open the file python?
probably you do not go to the script directory before open it.

You just should go to the directory using:
```bash
cd path/of/the/project/EPUB-to-PDF-master/
```

afterward, you can open it with:
```
python3 main.py
```
